#
# Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
sudo: required

language: java
jdk:
 - openjdk8

env:
  global:
    - GRADLE_OPTS="-Xms128m"

stages:
  - check
  - test
  - build

jobs:
  include:
    - stage: check
      name: Run Pravega CLI code analyzers
      before_script:
        - cd pravega-cli
      script:
        - ./gradlew check
    - stage: test
      name: Run Pravega CLI tests
      before_script:
        - cd pravega-cli
      script:
        - ./gradlew test
    - stage: dist
      name: Build Pravega CLI
      before_script:
        - cd pravega-cli
      script:
        - ./gradlew build

cache:
  directories:
   - ".gradle"
   - "$HOME/.gradle"
   - "$HOME/.m2"
